version: '3.5'
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: asdfjkl
      MYSQL_DATABASE: database_for_prisma
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d
    networks:
      - network_for_prisma
  prisma_app:
    build:
      context: .
      dockerfile: migrate.Dockerfile
    container_name: prisma_app
    env_file:
      - .env
    command: ./wait-for.sh mysql:3306 -- npx prisma migrate dev --name init
    depends_on:
      - mysql
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    networks:
      - network_for_prisma

volumes:
  db_data:
networks:
  network_for_prisma: