version: '3.9'
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - PRISMA_MIGRATION_NAME=${PRISMA_MIGRATION_NAME}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d
    networks:
      - default-network
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    environment:
      - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@mysql:${MYSQL_PORT}/${MYSQL_DATABASE}
    env_file:
      - ./.env
    depends_on:
      - mysql
    command: sh ./wait-for.sh mysql:${MYSQL_PORT} -- npm run start:dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - '3000:3000'
    networks:
      - default-network
volumes:
  db_data:
  node_modules:
networks:
  default-network: