version: '3.5'
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      PRISMA_MIGRATION_NAME: ${PRISMA_MIGRATION_NAME}
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d
    networks:
      - network_for_prisma
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: app
    env_file:
      - .env
    command: sh ./wait-for.sh mysql:${MYSQL_PORT} -- yarn start:dev
    depends_on:
      - mysql
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    networks:
      - network_for_prisma

volumes:
  db_data:
networks:
  network_for_prisma: