version: '3.9'
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - PRISMA_MIGRATION_NAME=${PRISMA_MIGRATION_NAME}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d
    networks:
      - default-network
  node-app-migrate:
    container_name: node-app-migrate
    build:
      context: .
      dockerfile: ./migrate.Dockerfile
    environment:
      - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@mysql:${MYSQL_PORT}/${MYSQL_DATABASE}
    depends_on:
      - mysql
    command: ./wait-for.sh mysql:3306 -- npx prisma migrate dev --name ${PRISMA_MIGRATION_NAME} # npx prisma migrate reset --force  # npx prisma db push
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - default-network
volumes:
  db_data:
  node_modules:
networks:
  default-network: