version: '3.5'
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      PRISMA_MIGRATION_NAME: ${PRISMA_MIGRATION_NAME}
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d
    networks:
      - network_for_prisma
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: app
    env_file:
      - .env
    tty: true
    stdin_open: true
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    networks:
      - network_for_prisma
  prisma-studio:
    image: node:lts-alpine3.17
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: sh ./wait-for.sh mysql:${MYSQL_PORT} -- npx prisma studio --port 5555 --browser none
    ports:
      - "5555:5555"
    env_file:
      - .env
    networks:
      - network_for_prisma
    depends_on:
      - mysql
      - app
volumes:
  db_data:
networks:
  network_for_prisma: